// Generated by lsc from speakerColor.ts

datatype Option<T> = None | Some(value: T)

function BitOr(x: int, y: int): int
  requires x >= 0 && y >= 0
  decreases x
{
  if x == 0 then y
  else if y == 0 then x
  else 2 * BitOr(x / 2, y / 2) + (if x % 2 == 1 || y % 2 == 1 then 1 else 0)
}

function JSRem(a: int, b: int): int
  requires b != 0
{
  var r := (if a < 0 then -a else a) % (if b < 0 then -b else b);
  if a < 0 then -r else r
}

function MathAbs(x: int): nat { if x >= 0 then x else -x }

const SPEAKER_PALETTE: seq<string> := ["#1d6775", "#355d8c", "#6b508a", "#8a4b66", "#975143", "#7a6224", "#42704c", "#4e6670"]

const speakerColorPalette: seq<string> := SPEAKER_PALETTE

method hashString(value: string) returns (res: int)
  ensures (res >= 0)
{
  var hash := 0;
  var i := 0;
  while (i < |value|)
  {
    hash := (((hash * 32) - hash) + (value[i] as int));
    hash := BitOr(hash, 0);
    i := (i + 1);
  }
  return MathAbs(hash);
}

method getSpeakerColor(key: Option<string>) returns (res: string)
  ensures (res in SPEAKER_PALETTE)
{
  var palette := SPEAKER_PALETTE;
  match key {
    case Some(i_key_val) =>
      if (|i_key_val| > 0) {
        var i_t0 := hashString(i_key_val);
        var index := JSRem(i_t0, |palette|);
        return palette[index];
      } else {
        return palette[0];
      }
    case None =>
      return palette[0];
  }
}
