-- 自動生成的 SQL 插入語句
-- 來源: raw_sample_data/2025-11-10-柏林自由會議ai-的角色.html
-- 生成時間: 2026-02-09T00:30:44.150Z

-- 使用 UPSERT 避免插入重複的 section_id（需要 PRIMARY KEY 約束）

UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628196, NULL, 628197, NULL, '<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/-DjvtvI4k9o?si=XQ_UUNtKTHCVgtnQ&amp;start=184" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628197, 628196, 628198, NULL, '<p><i>（我們全民就是超級智慧）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628198, 628197, 628199, '%E5%94%90%E9%B3%B3-3', '<p>柏林晚安。非常榮幸能來到這裡——這座城市向世人證明，當人們攜手並肩時，即使高牆也能倒塌。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628199, 628198, 628200, '%E5%94%90%E9%B3%B3-3', '<p>我認為柏林是討論 AI 角色的完美地點，因為這裡 1989 年的教訓非常簡單：當人們共同創造時，我們的表現將超越任何總體規劃。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628200, 628199, 628201, '%E5%94%90%E9%B3%B3-3', '<p>現在，我想分享我的想法：如何將 AI 從「成癮式智慧」（addictive intelligence）轉變為「輔助式智慧」（assistive intelligence）。我邀請各位與我一起，從「榨取式平臺」轉向能促進「關係健全度」（relational health）的協定。我認為，最重要的前沿模型並非存在於某個實驗室中。它是我們自身，是我們擴增的集體智慧（augmented collective intelligence）。就是我們全民。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628201, 628200, 628202, NULL, '<p><i>（缺口與啟示）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628202, 628201, 628203, '%E5%94%90%E9%B3%B3-3', '<p>五歲時，一場危及生命的心臟病，讓我體會到生命的迫切感。醫生告訴我，在接受心臟手術前，我只有 50% 的存活機率。在那之後，每個夜晚都像在擲硬幣。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628203, 628202, 628204, '%E5%94%90%E9%B3%B3-3', '<p>因此，我奉行一句格言，我稱之為「在消逝前發表」。我每天記錄下所學的一切，並發現了一個深刻的道理：在網路上發表，如果內容完美無缺，只會引來掌聲。但不完美，不完美才能邀請參與。我們的缺口，正是協作的開口。正如李歐納·柯恩所唱：「萬事萬物都有缺口，缺口就是光的入口。」</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628204, 628203, 628205, '%E5%94%90%E9%B3%B3-3', '<p>這對民主國家至關重要。我們必須公開過程，而不僅僅是最終政策。我們必須公開決策的「如何」與「為何」——讓人們看見——從而將批評者轉化為共同創造者。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628205, 628204, 628206, NULL, '<p><i>（極大化作業系統 vs. 多元宇宙）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628206, 628205, 628207, '%E5%94%90%E9%B3%B3-3', '<p>然而，當今數位時代 AI 的主導邏輯並非如此。這就是我所說的「極大化作業系統」（Max OS）——不是蘋果的 macOS，而是 Max OS。它追求的是互動率的極大化。它極大化觀看時間、點擊次數，並創造出一種寄生式的推薦引擎：以激怒帶起互動。過去十年的結果是，網路上的 PPM 非常高。我指的不是二氧化碳的百萬分濃度，雖然那也很重要。我指的是「每分鐘極化度」（polarization per minute）。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628207, 628206, 628208, '%E5%94%90%E9%B3%B3-3', '<p>長達十年「以激怒帶動互動」的模式，將我們的社群動態變成了腎上腺素工廠。它獎勵極端言論，淹沒了細微的差異。而這種信任破碎的環境，正是全球獨裁者所利用的。現在再加上生成式 AI，我們正以更快的速度產製著「廢料」（slop）：毫無關係營養的內容。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628208, 628207, 628209, '%E5%94%90%E9%B3%B3-3', '<p>因此，在這個旋轉的輪子上，問題不在於我們是否應該加速 AI 或停止 AI。問題在於，誰應該掌舵。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628209, 628208, 628210, NULL, '<p><i>（掌舵，而非空轉）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628210, 628209, 628211, '%E5%94%90%E9%B3%B3-3', '<p>現在，人們談論「人在迴圈中」（human in the loop）。但 AI 迴圈中的人就像倉鼠滾輪裡的倉鼠。也許感覺運動得很棒，但根本沒有在掌舵。我們需要將 AI 納入人本迴圈（AI in the loop of humanity）。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628211, 628210, 628212, '%E5%94%90%E9%B3%B3-3', '<p>這具體意味著什麼？這意味著我們共同掌握方向盤。我們利用 AI 作為輔助式智慧，幫助尋找交集，將衝突轉化——不是像火山爆發那樣的能量，而是將岩漿轉化為地熱能。為了實現強大的共同創造，我們可以將關係健全度最大化。一旦我們共同實現了這一點，我們就能攜手共創無限未來。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628212, 628211, 628213, NULL, '<p><i>（從憤怒到交集）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628213, 628212, 628214, '%E5%94%90%E9%B3%B3-3', '<p>這就是我們在臺灣具體所做的。在臺灣，我們深知壓力。壓力造就鑽石。根據 V-Dem 的數據，過去 12 年來，我們一直是全球極化攻擊的頭號目標。但我們適應了。我們學會用「利社會架構」取代反社會的媒體動態。我們知道，「引用嘲諷」或「酸」（dunk）是極化的根源。因此，我們建立的系統讓人無法酸任何人。相反地，我們只讓那些並非極端、而是在左右兩派之間搭橋的言論廣為流傳。這就是我們所說的「罕見共識」（uncommon ground），這是臺灣模式的核心。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628214, 628213, 628215, '%E5%94%90%E9%B3%B3-3', '<p>十年前，當共享乘車服務 Uber 進入臺灣時，引發了社會各界的激烈衝突。但我們使用了 Polis 這個橋接系統，來描繪人們實際達成共識的地方，就像一張團體自拍。僅僅三週，我們就將衝突轉化為每個人都能接受的政策選項。不是左翼，不是右翼，而是「上翼共識」（up-wing consensus）。如今，這種演算法已在全球範圍內被廣泛用作「社群備註」（Community Notes）。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628215, 628214, 628216, '%E5%94%90%E9%B3%B3-3', '<p>去年，當我們面臨來自網路深偽詐騙的新威脅時，許多人看到了臺裔 NVIDIA 執行長黃仁勳的臉。如果你點擊進去，黃仁勳會想送你免費的加密貨幣或提供一些投資建議。當然，那不是黃仁勳本人，那是運行在 NVIDIA GPU 上的他的深偽影像。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628216, 628215, 628217, '%E5%94%90%E9%B3%B3-3', '<p>然而，如果你單獨詢問臺灣民眾，他們都會說：「喔，政府應該遠離網路審查」，畢竟，正如我們的總統蔡博士所言，在網路自由方面，我們是全亞洲最自由的。那麼該怎麼辦？</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628217, 628216, 628218, '%E5%94%90%E9%B3%B3-3', '<p>我們向全臺灣的隨機號碼發送了 20 萬封簡訊，邀請召開公民大會來審議這個議題。最終隨機選出了 447 人，他們的背景組成與臺灣人口結構相同，以十人為一組，由 AI 協助主持。我們告訴這 45 個會議室：「你們必須提出一個能與視訊會議室中其他九個人產生共鳴的想法，才能被納入考量。」</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628218, 628217, 628219, '%E5%94%90%E9%B3%B3-3', '<p>一個會議室說：「讓我們顯著標示所有廣告，直到有人以數位方式簽署負責。」另一個會議室說：「如果有人因未簽署的投資詐騙損失了 700 萬，讓我們讓平臺（例如 Facebook）承擔全部責任。」也就是說，如果 Facebook 刊登了未簽署的廣告，它就必須支付這 700 萬元的損失。非常好的主意。另一個會議室說：「TikTok 當時在臺灣沒有辦公室。如果他們無視我們的規定，每無視一天，我們就把他們影片的連線速度降低 1%，但不是審查他們。」</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628219, 628218, 628220, '%E5%94%90%E9%B3%B3-3', '<p>基本上，這些想法在當天結束時由小型語言模型彙整起來，然後大家進行投票。這 447 人中，不分背景，超過 85% 的人表示同意。另外 15% 的人也能接受，認為這相當具有正當性。那是去年三月的事，到了五月，我們通過了《電子簽章法》的修正案。七月，我們通過了《詐防專法》。今年，這些深偽詐騙已經不復存在了。詐騙廣告下降了 90% 以上。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628220, 628219, 628221, NULL, '<p><i>（自由架構）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628221, 628220, 628222, '%E5%94%90%E9%B3%B3-3', '<p>柏林建立了橋樑，歐洲推動了互通性和可攜性——這也是橋樑。這種精神如今已使你能夠帶著你的資料、你的社交關係圖退出即時通訊應用程式，就像你更換電信業者時可以保留電話號碼一樣。這就是「自由架構」。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628222, 628221, 628223, '%E5%94%90%E9%B3%B3-3', '<p>因此，我們必須抵制數位殖民主義，以捍衛線上的行動自由，就像臺灣十年前抵制 Uber、去年抵制深偽廣告一樣。政策正在迅速跟上。現在我們明白，網路平臺也是公共場所。歐盟的《資料法》賦予我們資料可攜性，《數位市場法》則帶來了互通性。現在讓我們擴展這種精神。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628223, 628222, 628224, '%E5%94%90%E9%B3%B3-3', '<p>我們需要自由的協定，保障行動、結社、審議和安全。將它們視為公共的道路、橋樑和公園，而不是私人的圍牆花園。因為當退出成為可能時，平臺就必須在「關懷」（care）上競爭，而不是在「攫取」（capture）上競爭。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628224, 628223, 628225, NULL, '<p><i>（全民數位韌性）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628225, 628224, 628226, '%E5%94%90%E9%B3%B3-3', '<p>在接下來的專題討論中，我們將討論全民數位韌性，但可以說，獨裁者的劇本是全球性的。我們剛才聽到的間諜軟體、五毛農場、跨國鎮壓——我們的應對措施不能只是在傷害發生後進行本地下架，我們必須進行「預先澄清」，我們必須從設計上確保架構安全。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628226, 628225, 628227, '%E5%94%90%E9%B3%B3-3', '<p>我們需要「選擇性揭露」，只驗證我們憑證中相關的部分，例如「我已滿 18 歲」或「我是柏林人」，而無需透露我們的完整身份，拒絕起底。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628227, 628226, 628228, '%E5%94%90%E9%B3%B3-3', '<p>我們需要「邊緣 AI」，在我們的設備上運行的智慧防禦者，在無需監控、無需回傳資料的情況下保護我們的社群。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628228, 628227, 628229, '%E5%94%90%E9%B3%B3-3', '<p>我們需要「自帶政策」，我們當地的安全規則和審議規範需要伴隨我們跨越網路，這種方法對於反制跨國鎮壓至關重要。我們可以使用 AI 來檢測騷擾，但我們必須讓每個社群自行決定行為準則並做出最終判斷。「沒有我們的參與，就沒有關於我們的決定」，必須是我們自由架構的原則。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628229, 628228, 628230, NULL, '<p><i>（關懷六力）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628230, 628229, 628231, '%E5%94%90%E9%B3%B3-3', '<p>建立更強大的民主絕非易事。我們需要將這個過程視為在公民健身房中鍛鍊，並建立一個關懷迴圈。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628231, 628230, 628232, '%E5%94%90%E9%B3%B3-3', '<p>在牛津，我正在開發「關懷六力」（6-Pack of Care），包含六個基本動作：傾聽民意，信守承諾。讓人們投入過程，共同驗證結果。盡可能實現雙贏，並盡可能在地化。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628232, 628231, 628233, '%E5%94%90%E9%B3%B3-3', '<p>我們可以用這種方式訓練 AI 智慧體，超越僅僅追求分數最大化或遵守單薄的規則，這稱為「關係式對齊」，我們與關懷的過程對齊。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628233, 628232, 628234, '%E5%94%90%E9%B3%B3-3', '<p>因為如果我們將民主和政策辯論委託給聊天機器人，那就像派我們的機器人去健身房為我們舉重一樣。我確信它們的表現會令人印象深刻，可以舉起很重的重量，但我們的公民肌力將會萎縮。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628234, 628233, 628235, NULL, '<p><i>（⿻多元宇宙已經來臨）</i></p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628235, 628234, 628236, '%E5%94%90%E9%B3%B3-3', '<p>我們需要的超級智慧不是機器，而是我們以關懷進行協調的能力。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628236, 628235, 628237, '%E5%94%90%E9%B3%B3-3', '<p>我們全民，就是超級智慧。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628237, 628236, 628238, '%E5%94%90%E9%B3%B3-3', '<p>看見「萬物聯網」，我們將智慧聯網。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628238, 628237, 628239, '%E5%94%90%E9%B3%B3-3', '<p>看見「機器學習」，我們將協力學習。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628239, 628238, 628240, '%E5%94%90%E9%B3%B3-3', '<p>看見「虛擬實境」，我們將實境共享。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628240, 628239, 628241, '%E5%94%90%E9%B3%B3-3', '<p>看見「用戶體驗」，我們將體驗人際。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628241, 628240, 628242, '%E5%94%90%E9%B3%B3-3', '<p>聽說「奇點即將接近」—— 多元宇宙，已經來臨。</p>');
UPSERT INTO speech_content (filename, nest_filename, nest_display_name, section_id, previous_section_id, next_section_id, section_speaker, section_content) VALUES ('2025-11-10-柏林自由會議ai-的角色', NULL, NULL, 628242, 628241, NULL, '%E5%94%90%E9%B3%B3-3', '<p>謝謝大家。</p>');

-- 插入演講-講者關係到 speech_speakers 表
-- 使用 INSERT OR IGNORE INTO 避免插入重複的 (speech_filename, speaker_route_pathname) 組合

INSERT OR IGNORE INTO speech_speakers (speech_filename, speaker_route_pathname) VALUES ('2025-11-10-柏林自由會議ai-的角色', '%E5%94%90%E9%B3%B3-3');
